/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateBorrarArgs } from "./CreateBorrarArgs";
import { UpdateBorrarArgs } from "./UpdateBorrarArgs";
import { DeleteBorrarArgs } from "./DeleteBorrarArgs";
import { BorrarFindManyArgs } from "./BorrarFindManyArgs";
import { BorrarFindUniqueArgs } from "./BorrarFindUniqueArgs";
import { Borrar } from "./Borrar";
import { ProjectFindManyArgs } from "../../project/base/ProjectFindManyArgs";
import { Project } from "../../project/base/Project";
import { BorrarService } from "../borrar.service";

@graphql.Resolver(() => Borrar)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class BorrarResolverBase {
  constructor(
    protected readonly service: BorrarService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Borrar",
    action: "read",
    possession: "any",
  })
  async _borrarsMeta(
    @graphql.Args() args: BorrarFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Borrar])
  @nestAccessControl.UseRoles({
    resource: "Borrar",
    action: "read",
    possession: "any",
  })
  async borrars(
    @graphql.Args() args: BorrarFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Borrar[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Borrar",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Borrar, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Borrar",
    action: "read",
    possession: "own",
  })
  async borrar(
    @graphql.Args() args: BorrarFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Borrar | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Borrar",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Borrar)
  @nestAccessControl.UseRoles({
    resource: "Borrar",
    action: "create",
    possession: "any",
  })
  async createBorrar(
    @graphql.Args() args: CreateBorrarArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Borrar> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Borrar",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Borrar"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Borrar)
  @nestAccessControl.UseRoles({
    resource: "Borrar",
    action: "update",
    possession: "any",
  })
  async updateBorrar(
    @graphql.Args() args: UpdateBorrarArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Borrar | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Borrar",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Borrar"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Borrar)
  @nestAccessControl.UseRoles({
    resource: "Borrar",
    action: "delete",
    possession: "any",
  })
  async deleteBorrar(
    @graphql.Args() args: DeleteBorrarArgs
  ): Promise<Borrar | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Project])
  @nestAccessControl.UseRoles({
    resource: "Borrar",
    action: "read",
    possession: "any",
  })
  async task(
    @graphql.Parent() parent: Borrar,
    @graphql.Args() args: ProjectFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Project[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Project",
    });
    const results = await this.service.findTask(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
